owner: SethuK-ND
repo: Upptime

sites:
  - name: Tamilmv
    url: https://1tamilmv.tf
  - name: Tamilblasters
    url: https://1tamilblasters.dad

status-website:
  baseUrl: /Upptime
  name: Movie Website Status
  introTitle: "**Find all Movie resources here**"

workflowSchedule:
  uptime: "*/360 * * *  *"
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *" 