owner: SethuK-ND
repo: Upptime

sites:
  - name: Tamilmv
    url: https://www.1tamilmv.tf/
  - name: Tamilblasters
    url: https://1tamilblasters.dad

assignees:
  - SethuK-ND

status-website:
  theme: dark
  logoUrl: https://upptime.js.org/img/icon.svg
  baseUrl: /Upptime
  name: Movie Website Status
  introTitle: "**Find the status of all movie resources here**"
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/$OWNER/$REPO). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: false

workflowSchedule:
  uptime: "0 * * * *"
  graphs: "0 * * * *"
  responseTime: "0 * * * *"
  staticSite: "0 * * * *"
  summary: "0 * * * *"
  updateTemplate: "0 */6 * * *"
  updates: "0 */6 * * *"

