owner: SethuK-ND
repo: Upptime

sites:
  - name: Tamilmv
    url: https://1tamilmv.tf
  - name: Tamilblasters
    url: https://1tamilblasters.dad

status-website:
  baseUrl: /Upptime
  name: Movie Website Status
  introTitle: "**Find the status of all movie resources here**"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Website
      href: https://aakritsubedi9.com.np 
workflowSchedule:
  uptime: "0 * * * *"
  graphs: "0 * * * *"
  responseTime: "0 * * * *"
  staticSite: "0 * * * *"
  summary: "0 * * * *"
  updateTemplate: "0 * * * *"
  updates: "0 * * * *"
