owner: SethuK-ND
repo: Upptime

sites:
  - name: TMV
    url: https://www.1tamilmv.tf/
  - name: TBL
    url: https://1tamilblasters.dad
  - name: BTDigg
    url: https://btdig.com/index.htm
  - name: TGX
    url: https://torrentgalaxy.to/

assignees:
  - SethuK-ND

status-website:
  theme: dark
  logoUrl: https://upptime.js.org/img/icon.svg
  baseUrl: /Upptime
  name: Movie Website Status
  introTitle: "**Find the status of all movie resources here**"
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/SethuK-ND/Upptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  scripts:
    status-website:
  customHeadHtml: |
    <script src="https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js"></script>
  customBodyHtml: |
    <script>
      async function fetchAndParseYAML(url) {
          try {
              const response = await fetch(url);
              if (!response.ok) {
                  throw new Error(`URL error: ${response.status}`);
              }
              const yamlData = await response.text();
              const parsedData = jsyaml.load(yamlData);
              const sitesData = parsedData.sites;
              console.log(sitesData);
              
              // Convert sitesData to a string for saving
              const sitesText = JSON.stringify(sitesData, null, 2);
              saveToFile(sitesText, 'sitesData.txt');
          } catch (error) {
              console.error('Error fetching or parsing YAML:', error);
          }
      }

      function saveToFile(data, filename) {
          const blob = new Blob([data], { type: 'text/plain' });
          const url = URL.createObjectURL(blob);
          const a = document.createElement('a');
          a.href = url;
          a.download = filename;
          document.body.appendChild(a);
          a.click();
          document.body.removeChild(a);
          URL.revokeObjectURL(url);
      }

      fetchAndParseYAML('https://raw.githubusercontent.com/SethuK-ND/Upptime/master/.upptimerc.yml');
    </script>

workflowSchedule:
  uptime: "0 * * * *"
  graphs: "0 * * * *"
  responseTime: "0 * * * *"
  staticSite: "0 * * * *"
  summary: "0 * * * *"
  updateTemplate: "0 */6 * * *"
  updates: "0 */6 * * *"

